pipeline {
    agent any

    stages {
        stage('Install dependencies') {
            steps {
                sh 'python3 -m pip install --upgrade pip'
                sh 'python3 -m pip install -r requirements.txt'
            }
        }
        stage('Run tests') {
            steps {
                sh 'python3 -m pytest'
            }
        }
        stage('Package with PyInstaller') {
            steps {
                sh 'python3 -m pip install pyinstaller'
                sh 'python3 -m pyinstaller --onefile sources/add2vals.py'
            }
        }
        stage('Archive Build') {
            steps {
                archiveArtifacts artifacts: 'dist/add2vals', onlyIfSuccessful: true
            }
        }
    }
}

